= Common Language Differences
:toc:

Common Language Differences (Julia, PowerShell, Python, JavaScript, et al) This isn't intended to cover all languages, just the ones I'm currently using.

This is a github repo instead of a github gist because when editing from the browser you can't do a preview of a gist, but you can of a repo readme.

:numbered:

== String Interpolation

[%header]
|===
| language   | syntax                                                | notes

| C++        | nope (but see std::format)                            |
| C#	     | `$"Hello, {name} ({name.Length} letters)"`            | (braces)
| JavaScript | `\`Hello, ${name} (${name.length} letters)\``         | (braces)
| Julia	     | `"Hello, $name ($(length(name)) letters)"`            | (parens)
| PowerShell | `"Hello, $name or ${name} ($($name.Length) letters)"` | (parens)
| Python(1)  | `f"Hello, {name} ({len(name)} letters)"`              | (braces)
| Rust       |                                                     	 |
|===

(1) Python works in single or double quotes

== String functions

[%header]
|===
|Language |Length |Substring |Contains 

|C/C++
|`strlen(s)` +
`s.size()` (or `s.length()`)
| C: nope +
`s.substr(start, len)` +
`s.substr(start)` # to end
| `s.find("abc") != std::string::npos` +
boost::algorithm::starts_with(s, "abc")^(1)^ +
boost::algorithm::ends_with(s, "abc")^(1)^

|C#
|`s.Length`
|`s.Substring(start, len)` +
`s.Substring(start)` # to end
|`s.Contains("abc")` +
`s.StartsWith("abc")` +
`s.EndsWith("abc")`

|PowerShell
|`s.Length`
|`s.Substring(1, len)` +
`s.Substring(start)`
|`s -clike '*abc*"` +
`s -ilike "*abc*"` # or -like
|===

(1) C++ (from https://stackoverflow.com/a/42844629)
[source,c++]
----
static bool endsWith(const std::string& str, const std::string& suffix)
{
    return str.size() >= suffix.size() && 0 == str.compare(str.size()-suffix.size(), suffix.size(), suffix);
}
static bool startsWith(const std::string& str, const std::string& prefix)
{
    return str.size() >= prefix.size() && 0 == str.compare(0, prefix.size(), prefix);
}
----

== Collections

https://docs.julialang.org/en/v1/base/collections/#Dictionaries
https://en.wikibooks.org/wiki/Introducing_Julia/Dictionaries_and_sets

.julia
[source,julia]
----
my_dict = Dict{String,Int64}()
my_dict = Dict("a"=>1,"b"=2) # or iterable returning tuple
my_dict["a"] ; my_dict["c"] = 3 # or get(collection, key, default)
my_dict["d"] # throws
hasdict(my_dict, "d")
for (key, value) in my_dict
    @show key, value
end

my_tuple = (1,2,3)
my_array [1,2,3] # aka vector  

julia> [[1,2,3] , [4,5,6]] # array of arrays  
2-element Array{Array{Int64,1},1}:
[1, 2, 3]
[4, 5, 6]

julia> [[1,2,3] [4,5,6]] # 2d array 
3×2 Array{Int64,2}:
1 4
2 5
3 6

julia> [[1 2 3] ; [4 5 6]] # 2d array  
2×3 Array{Int64,2}:
1 2 3
4 5 6
----

== Exceptions

[cols="h,a"]
|===
|C++ |todo
|C# |todo
|JavaScript |todo

|Julia |[source,julia]
----
try
  throw(DomainError(x, "argument must be nonnegative"))
  error("something bad happened") # throws ErrorException
catch ex
  ...
end
----
See https://docs.julialang.org/en/v1/manual/control-flow/#Built-in-Exceptions[Built-in-Exceptions] for more exception types. 

|Powershell |todo
|Python |todo
|Rust |todo

|===


== List Comprensions

[%header]
|===
|Julia |Python

|`osquares = [x * x for x in 1:10 if x % 2 == 1]`
|`osquares = [x * x for x in range(10) if x % 2 == 1]`

|===


== Logging

.powershell
[source,powershell]
----
function log_error($msg) { Write-Host  -ForegroundColor Red    ">> ERROR $msg" }
function log_warn($msg) { Write-Host   -ForegroundColor Yellow ">> WARN  $msg" }
function log_OK($msg) { Write-Host     -ForegroundColor Green  ">> OK    $msg" }
function log_DONE($msg) { Write-Host   -ForegroundColor Green  ">> DONE  $msg" }
function log_info($msg) { Write-Host   -ForegroundColor Cyan   ">> INFO  $msg" }
function log_debug($msg) { Write-Host  -ForegroundColor Blue   ">> DEBUG $msg" }
----

.julia
[source,julia]
----
log_error(msg) = printstyled(">> ERROR $msg" ; color = :red)
log_warn(msg) =  printstyled(">> WARN  $msg" ; color = :yellow)
log_OK(msg) =    printstyled(">> OK    $msg" ; color = :green)
log_DONE(msg) =  printstyled(">> DONE  $msg" ; color = :green)
log_info(msg) =  printstyled(">> INFO  $msg" ; color = :cyan)
log_debug(msg) = printstyled(">> DEBUG $msg" ; color = :blue)
----

== Null or missing values

[cols="<.<,<.<,<.<,<.<,<.<,<.<,<.<", options="header"]
|=== 
| C/C++ | C# | JavaScript | Julia^(1)^ | PowerShell^(2)^ | Python | Rust

| `a == NULL` +
  `a == nullptr`
| `a == null`
| `a === null` +
  `a === undefined` +
  `a == null` (null or undefined)
| `a === nothing` +
  `isnothing(a)` +
  `ismissing(a)`
| `$null -eq $a`
| `a is None`
| (rust todo)
|===

(1) Julia: `nothing` generates errors in expressions, `missing` propagates silently 

(2) PowerShell: "You may have noticed that I always place the $null on the left when checking for $null in my examples. This is intentional and accepted as a PowerShell best practice. There are some scenarios where placing it on the right doesn't give you the expected result." -- https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null
